#!/usr/bin/env python3
"""Extract Firefox cookies to Netscape cookies.txt format for yt-dlp.

No browser extension. No manual paste. No need to close Firefox.
Opens cookies.sqlite in read-only + immutable mode (bypasses Firefox's
write locks; reads the last-committed state directly) and writes a
Netscape-format cookies file (0600 perms).

Usage:
    extract-firefox-cookies.py [--profile PATH] [--domain PATTERN]
                               [--output PATH]

Defaults:
    --profile   auto-detect first *.default-esr in ~/.mozilla/firefox/
                (falls back to *.default)
    --domain    youtube google accounts.google (LIKE-pattern fragments;
                repeatable)
    --output    /tmp/yt-cookies.txt

Firefox-side prereqs (one-time setup; cookies must actually persist
to the on-disk store for sqlite3 to see them):
    1. about:preferences#privacy
       - Enhanced Tracking Protection: Standard (NOT Strict — Total
         Cookie Protection in Strict partitions the cookie store in a
         way that yt-dlp can't follow)
       - Uncheck "Delete cookies and site data when Firefox is closed"
       - History: "Remember history" (not "Never remember")
    2. Log into the target site (e.g. YouTube) in a regular,
       non-private window
    3. Visit the site briefly so the session writes to cookies.sqlite

Then run this script while Firefox stays open. The atomic backup
snapshot doesn't require Firefox to close.

After use:
    yt-dlp --cookies /tmp/yt-cookies.txt <URL>
    shred -u /tmp/yt-cookies.txt   # when done
"""

import argparse
import os
import sqlite3
import sys
from datetime import datetime
from pathlib import Path


DEFAULT_DOMAIN_LIKES = ["youtube", "google", "accounts.google"]
DEFAULT_OUTPUT = Path("/tmp/yt-cookies.txt")


def find_firefox_profile():
    base = Path.home() / ".mozilla" / "firefox"
    if not base.is_dir():
        return None
    for pattern in ("*.default-esr", "*.default"):
        matches = sorted(base.glob(pattern))
        if matches:
            return matches[0]
    return None


def extract(cookies_db, domain_likes, output_path):
    domain_clauses = " OR ".join(f"host LIKE '%{d}%'" for d in domain_likes)

    # immutable=1 tells sqlite to treat the file as read-only media,
    # which bypasses Firefox's write locks. Returns last-committed
    # state (any in-flight WAL writes are ignored — fine for cookies
    # extraction; the user only needs cookies that are already persisted).
    uri = f"file:{cookies_db}?mode=ro&immutable=1"
    con = sqlite3.connect(uri, uri=True)
    rows = con.execute(f"""
        SELECT host, path, isSecure, expiry, name, value
        FROM moz_cookies
        WHERE {domain_clauses}
        ORDER BY host, name
    """).fetchall()
    con.close()

    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by extract-firefox-cookies.py",
        f"# Source profile: {cookies_db.parent}",
        f"# Generated: {datetime.now().isoformat(timespec='seconds')}",
        "",
    ]
    for host, path, is_secure, expiry, name, value in rows:
        include_subs = "TRUE" if host.startswith(".") else "FALSE"
        secure = "TRUE" if is_secure else "FALSE"
        lines.append(
            f"{host}\t{include_subs}\t{path}\t{secure}\t{expiry}\t{name}\t{value}"
        )

    output_path.write_text("\n".join(lines) + "\n")
    os.chmod(output_path, 0o600)
    return len(rows)


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--profile",
        type=Path,
        help="Firefox profile path (auto-detects *.default-esr if omitted)",
    )
    parser.add_argument(
        "--domain",
        action="append",
        help=(
            "Domain LIKE-pattern fragment (repeatable; default: "
            "youtube google accounts.google)"
        ),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output cookies.txt path (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args()

    profile = args.profile or find_firefox_profile()
    if not profile or not profile.is_dir():
        sys.exit(f"ERROR: Firefox profile not found (tried: {profile})")

    cookies_db = profile / "cookies.sqlite"
    if not cookies_db.is_file():
        sys.exit(f"ERROR: cookies.sqlite not found at {cookies_db}")

    domain_likes = args.domain if args.domain else DEFAULT_DOMAIN_LIKES
    count = extract(cookies_db, domain_likes, args.output)

    print(f"✓ Wrote {args.output} ({count} cookies, profile: {profile.name})")
    if count == 0:
        print(
            "\nWARNING: Zero cookies extracted. Likely causes:\n"
            "  - Firefox set to ETP Strict (Total Cookie Protection partitions "
            "cookies)\n"
            "  - 'Delete cookies on close' is enabled\n"
            "  - You were in a private window when logging in\n"
            "  - You haven't logged into the target site yet\n"
            "See the docstring for the full prereq checklist.",
            file=sys.stderr,
        )
        sys.exit(2)

    print(f"  Use with: yt-dlp --cookies {args.output} <URL>")


if __name__ == "__main__":
    main()
