#!/usr/bin/env python3
"""
Regenerate the '## Associated Nodes' section of a node from body references.

Scans the node body for every [`/path/to/...`] reference (excluding the
Associated Nodes section itself and self-references), groups by target
type, and rewrites the section.

Usage:
  associate.py PATH            # regenerate one node
  associate.py --all           # regenerate every node
  associate.py --check         # report stale sections (exit 1 if any)
"""

import argparse
import re
import sys
from pathlib import Path
from collections import defaultdict

REPO_ROOT = Path(__file__).resolve().parent.parent

CONTENT_DIRS = [
    "people", "organizations", "documents", "events",
    "transcripts", "news", "books", "locations", "findings",
]

# Display order of groups in the Associated Nodes section
GROUP_ORDER = [
    "People",
    "Organizations",
    "Events",
    "Documents",
    "Transcripts",
    "News",
    "Books",
    "Locations",
    "Findings",
]

DIR_TO_GROUP = {
    "people": "People",
    "organizations": "Organizations",
    "events": "Events",
    "documents": "Documents",
    "transcripts": "Transcripts",
    "news": "News",
    "books": "Books",
    "locations": "Locations",
    "findings": "Findings",
}

LINK_PATTERN = re.compile(r"\[`(/[^`]+)`\]")


def extract_links(text, exclude_self=None):
    links = set(LINK_PATTERN.findall(text))
    if exclude_self:
        links.discard(exclude_self)
        links.discard(f"/{exclude_self}")
    return links


def group_links(links):
    groups = defaultdict(list)
    for link in links:
        parts = link.strip("/").split("/")
        if len(parts) < 2:
            continue
        group = DIR_TO_GROUP.get(parts[0], parts[0].capitalize())
        groups[group].append(link)
    return groups


def generate_section(groups):
    lines = ["## Associated Nodes", ""]
    lines.append("<!-- Auto-generated by scripts/associate.py. Do not hand-edit. -->")
    lines.append("")
    for group in GROUP_ORDER:
        if group not in groups:
            continue
        links = sorted(set(groups[group]))
        lines.append(f"### {group}")
        lines.append("")
        for link in links:
            lines.append(f"- [`{link}`]")
        lines.append("")
    # Trailing separator before whatever section comes next
    lines.append("---")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n\n"


def replace_section(text, new_section):
    """Replace existing Associated Nodes section, or insert before Open Questions.

    `new_section` is expected to end with a trailing '---\\n\\n' separator.
    Any existing separator preceding the next H2 is consumed as part of the
    replaced block so we don't duplicate separators.
    """
    match = re.search(r"^## Associated Nodes\s*$", text, re.MULTILINE)
    if match:
        start = match.start()
        after = text[match.end():]
        next_h2 = re.search(r"^## ", after, re.MULTILINE)
        end = match.end() + next_h2.start() if next_h2 else len(text)
        prefix = text[:start].rstrip() + "\n\n"
        suffix = text[end:]
        return prefix + new_section + suffix

    # No existing section — insert before Open Questions
    oq = re.search(r"^## Open Questions", text, re.MULTILINE)
    if oq:
        prefix = text[:oq.start()].rstrip() + "\n\n"
        suffix = text[oq.start():]
        return prefix + new_section + suffix

    # Append at end
    return text.rstrip() + "\n\n" + new_section


def associate_node(node_path, dry_run=False):
    text = node_path.read_text()
    self_id = str(node_path.relative_to(REPO_ROOT)).removesuffix(".md")

    # Remove existing Associated Nodes section before scanning (avoid self-amplification)
    scan_text = text
    existing = re.search(
        r"^## Associated Nodes\s*$.*?(?=^## |\Z)",
        text, re.MULTILINE | re.DOTALL,
    )
    if existing:
        scan_text = text[:existing.start()] + text[existing.end():]

    links = extract_links(scan_text, exclude_self=self_id)
    groups = group_links(links)
    new_section = generate_section(groups)
    new_text = replace_section(text, new_section)

    if new_text != text:
        if not dry_run:
            node_path.write_text(new_text)
        return True
    return False


def collect_all_nodes():
    nodes = []
    for d in CONTENT_DIRS:
        cd = REPO_ROOT / d
        if cd.is_dir():
            nodes.extend(sorted(cd.glob("*.md")))
    return nodes


def main():
    parser = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("path", nargs="?")
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--check", action="store_true",
                        help="Report stale sections without writing")
    args = parser.parse_args()

    if args.check or args.all:
        nodes = collect_all_nodes()
        changed = 0
        for node in nodes:
            if associate_node(node, dry_run=args.check):
                changed += 1
                print(f"  {'STALE ' if args.check else 'UPDATE'}  {node.relative_to(REPO_ROOT)}")
        if args.check:
            print(f"\n{changed} stale Associated Nodes sections")
            sys.exit(1 if changed else 0)
        print(f"\n{changed} nodes updated")
    elif args.path:
        node = Path(args.path).resolve()
        if not node.exists():
            sys.exit(f"ERROR: {node} not found")
        if associate_node(node):
            print(f"✓ Updated {node.relative_to(REPO_ROOT)}")
        else:
            print(f"  No change: {node.relative_to(REPO_ROOT)}")
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
