#!/usr/bin/env python3
"""
Regenerate the auto-generated build-state tables in CLAUDE.md from
node frontmatter.

The generated block replaces content between:
    <!-- BUILD-STATE-START: auto-generated by scripts/build-state.py -->
    <!-- BUILD-STATE-END -->

Content outside the markers is preserved.

Usage:
  build-state.py               # print to stdout
  build-state.py --update      # rewrite CLAUDE.md section
  build-state.py --check       # exit 1 if out of sync
"""

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml  # noqa: F401  (kept for early ImportError guidance)
except ImportError:
    print("ERROR: Install PyYAML: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

from lib._common import (
    REPO_ROOT,
    content_dirs,
    parse_frontmatter as _parse_frontmatter_with_body,
)

CLAUDE_MD = REPO_ROOT / "CLAUDE.md"

# Per-directory display name + grouping mode for the build-state
# block. Three modes:
#   archetype-table — person nodes (Status + Archetype columns)
#   kind-table      — orgs / docs / events / transcripts / media
#                     (Status + Kind columns)
#   status-list     — simple list with status suffix
# ``display`` and ``mode`` are presentation-only; ``dir`` comes from
# ``lib._common.content_dirs()``.
_DISPLAY_AND_MODE = {
    "people":          ("People",         "archetype-table"),
    "organizations":   ("Organizations",  "kind-table"),
    "events":          ("Events",         "kind-table"),
    "documents":       ("Documents",      "kind-table"),
    "transcripts":     ("Transcripts",    "kind-table"),
    "media":           ("Media",          "kind-table"),
    "locations":       ("Locations",      "status-list"),
    "findings":        ("Findings",       "status-list"),
    "investigations":  ("Investigations", "status-list"),
}

# Render order matches CLAUDE.md's expected sequence (people first, then
# organizations, then events, …) — preserved by enumerating
# _DISPLAY_AND_MODE in its dict-insertion order rather than schema order
# (which has documents before events).
NODE_DIRS = [
    (d, *_DISPLAY_AND_MODE[d])
    for d in _DISPLAY_AND_MODE
    if d in content_dirs()
]

MARKER_START = "<!-- BUILD-STATE-START: auto-generated by scripts/build-state.py -->"
MARKER_END = "<!-- BUILD-STATE-END -->"


def parse_frontmatter(text):
    """Thin wrapper around ``lib._common.parse_frontmatter`` that returns
    just the frontmatter dict (build-state doesn't consume the body) and
    coerces None to {} so callers don't need a None check."""
    fm, _ = _parse_frontmatter_with_body(text)
    return fm or {}


def collect_nodes():
    result = {}
    for d, _, _ in NODE_DIRS:
        dp = REPO_ROOT / d
        nodes = []
        if dp.is_dir():
            for f in sorted(dp.glob("*.md")):
                fm = parse_frontmatter(f.read_text())
                nodes.append({
                    "id": fm.get("id") or str(f.relative_to(REPO_ROOT).with_suffix("")),
                    "status": fm.get("status", "?"),
                    "archetype": fm.get("archetype"),
                    "kind": fm.get("kind"),
                })
        result[d] = nodes
    return result


def format_status(s):
    return f"**{s}**" if s == "in-progress" else s


def generate_block(nodes_by_dir):
    lines = [MARKER_START, ""]
    for d, display, mode in NODE_DIRS:
        nodes = nodes_by_dir.get(d, [])
        lines.append(f"### {display} ({len(nodes)})")
        lines.append("")
        if not nodes:
            lines.append("*No nodes yet.*")
            lines.append("")
            continue
        if mode == "archetype-table":
            lines.append("| Node | Status | Archetype |")
            lines.append("|---|---|---|")
            for n in nodes:
                lines.append(f"| `/{n['id']}` | {format_status(n['status'])} | {n['archetype'] or '—'} |")
        elif mode == "kind-table":
            lines.append("| Node | Status | Kind |")
            lines.append("|---|---|---|")
            for n in nodes:
                lines.append(f"| `/{n['id']}` | {format_status(n['status'])} | {n['kind'] or '—'} |")
        else:
            for n in nodes:
                suffix = f" — {n['status']}" if n['status'] != "?" else ""
                lines.append(f"- `/{n['id']}`{suffix}")
        lines.append("")
    lines.append(MARKER_END)
    return "\n".join(lines)


def replace_block(claude_text, new_block):
    pattern = re.compile(
        re.escape(MARKER_START.split(":")[0]) + r".*?" + re.escape(MARKER_END),
        re.DOTALL,
    )
    if not pattern.search(claude_text):
        raise ValueError("CLAUDE.md does not contain BUILD-STATE markers")
    return pattern.sub(new_block, claude_text)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--update", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    nodes_by_dir = collect_nodes()
    new_block = generate_block(nodes_by_dir)

    if not (args.update or args.check):
        print(new_block)
        return

    if not CLAUDE_MD.exists():
        print(f"ERROR: {CLAUDE_MD} not found", file=sys.stderr)
        sys.exit(1)

    current = CLAUDE_MD.read_text()
    try:
        updated = replace_block(current, new_block)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    if args.check:
        if current != updated:
            print("CLAUDE.md build state is OUT OF SYNC.", file=sys.stderr)
            print("Run: python3 scripts/build-state.py --update", file=sys.stderr)
            sys.exit(1)
        print("CLAUDE.md build state in sync.")
        return

    if current == updated:
        print("CLAUDE.md already in sync — no changes.")
        return
    CLAUDE_MD.write_text(updated)
    print(f"✓ Updated {CLAUDE_MD.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
