"""boundary check — cross-layer ResearchContext check.

Verifies the rendered node body (outside ``## Associated Nodes``)
matches what ``build-from-research.py --dry-run`` would regenerate
from the current artifact. Divergence means the artifact drifted from
the node, the node was hand-edited, or the renderer changed.

Reads ``ctx.regenerated_body`` (a lazy ResearchContext property added
by C16). The first cross-layer check to access the property spawns
``python3 build-from-research.py --dry-run --no-validate``; the
result is cached for the lifetime of the context so a second cross-
layer consumer (when one surfaces) doesn't respawn.

Consumes ``ctx.node_path`` (set by the review-coverage orchestrator
after target-node resolution) for reading the current rendered body.

Origin: shipped at commit ``0a56989`` (D.4 — introduction of Phase III
review-coverage.py) as one of four mechanical checks
(Coverage / Boundary / Stub-linking / OQ dedup). The D.4 launch
itself dogfooded the design — running the new tool against the
existing Fravor artifact reported 5 errors (boundary divergence +
4 orphan OQ items), which the D.4 commit message described as
"exactly the D.5 pilot-rebuild gap the tool is designed to
surface." Same self-validating dogfood pattern as
description_token_drift, which caught Fravor's "Congressional"
drift on first run.

Three drift classes the check protects against:

  1. Artifact-to-node desync — artifact was edited and re-rendered;
     committer forgot to commit the regenerated node, or the inverse
     (node hand-edit lost on next regen).
  2. Hand-edits to the rendered node body — contributor edited the
     node directly rather than the artifact, breaking the artifact-
     as-source-of-truth invariant.
  3. Renderer changes — build-from-research.py logic changed and the
     committed node bodies haven't been regenerated to match.

Comparison is byte-equal after the Associated Nodes section is
excised from both sides. Strict byte-equality is load-bearing: the
renderer is deterministic per design (same artifact + same renderer
produces identical output), and this check enforces that determinism
across the corpus.

Migration: ``0a56989`` (introduction; inline subprocess machinery in
review-coverage.py) → ``4b1cfd3`` (BACKLOG C16; subprocess + caching
moved to ``ResearchContext.regenerated_body`` lazy property — closed
the cluster's deferred Issue #5 even though no second consumer exists
today, on the judgment that a future cross-layer check addition
shouldn't have to re-implement subprocess + caching machinery) →
``363212d`` (C11 session 3 lift to per-module shape). C18 confirmed
byte-identity through both moves.
"""

import re

from checks import Issue


CHECK_NAME = "boundary"


def _excise_associated_nodes(text):
    """Strip the '## Associated Nodes' section (up to the next H2) so
    the boundary diff focuses on the Phase II-rendered body. The
    Associated Nodes section is regenerated by associate.py post-build
    and is not part of build-from-research.py's deterministic output
    (it emits a placeholder).
    """
    pattern = re.compile(
        r"^## Associated Nodes\s*$.*?(?=^## |\Z)",
        re.MULTILINE | re.DOTALL,
    )
    return pattern.sub("", text).rstrip() + "\n"


def check(ctx):
    if ctx.node_path is None:
        return

    regenerated, error = ctx.regenerated_body
    if error is not None:
        yield Issue(
            ctx.rel, "error",
            f"Boundary: {error}",
            check_name=CHECK_NAME,
        )
        return

    current = ctx.node_path.read_text()
    regen_excised = _excise_associated_nodes(regenerated).strip()
    current_excised = _excise_associated_nodes(current).strip()

    if regen_excised != current_excised:
        yield Issue(
            ctx.rel, "error",
            "Boundary: node body diverges from build-from-research.py output. "
            "Either the artifact drifted from the node, or the node was "
            "hand-edited. Re-run build-from-research.py to resync.",
            check_name=CHECK_NAME,
        )
