"""boundary check — cross-layer ResearchContext check.

Verifies the rendered node body (outside ``## Associated Nodes``)
matches what ``build-from-research.py --dry-run`` would regenerate
from the current artifact. Divergence means the artifact drifted from
the node, the node was hand-edited, or the renderer changed.

Spawns ``python3 build-from-research.py --dry-run --no-validate`` per
artifact (subprocess overhead; logged as BACKLOG C16 candidate for
memoization if a second consumer of the regenerated body ever surfaces).

Consumes ``ctx.path`` and ``ctx.node_path`` (set by the review-coverage
orchestrator after target-node resolution).
"""

import re
import subprocess
from pathlib import Path

from checks import Issue


CHECK_NAME = "boundary"


_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_BUILD_FROM_RESEARCH = _REPO_ROOT / "scripts" / "build-from-research.py"


def _excise_associated_nodes(text):
    """Strip the '## Associated Nodes' section (up to the next H2) so
    the boundary diff focuses on the Phase II-rendered body. The
    Associated Nodes section is regenerated by associate.py post-build
    and is not part of build-from-research.py's deterministic output
    (it emits a placeholder).
    """
    pattern = re.compile(
        r"^## Associated Nodes\s*$.*?(?=^## |\Z)",
        re.MULTILINE | re.DOTALL,
    )
    return pattern.sub("", text).rstrip() + "\n"


def check(ctx):
    if ctx.node_path is None:
        return
    try:
        proc = subprocess.run(
            ["python3", str(_BUILD_FROM_RESEARCH),
             str(ctx.path), "--dry-run", "--no-validate"],
            capture_output=True, text=True, timeout=60,
        )
    except subprocess.TimeoutExpired:
        yield Issue(
            ctx.rel, "error",
            "Boundary: build-from-research.py timed out during dry-run",
            check_name=CHECK_NAME,
        )
        return

    if proc.returncode != 0:
        detail = (proc.stderr.strip() or proc.stdout.strip())[:200]
        yield Issue(
            ctx.rel, "error",
            f"Boundary: build-from-research.py exited {proc.returncode}: {detail}",
            check_name=CHECK_NAME,
        )
        return

    regenerated = proc.stdout
    current = ctx.node_path.read_text()

    regen_excised = _excise_associated_nodes(regenerated).strip()
    current_excised = _excise_associated_nodes(current).strip()

    if regen_excised != current_excised:
        yield Issue(
            ctx.rel, "error",
            "Boundary: node body diverges from build-from-research.py output. "
            "Either the artifact drifted from the node, or the node was "
            "hand-edited. Re-run build-from-research.py to resync.",
            check_name=CHECK_NAME,
        )
