"""boundary check — cross-layer ResearchContext check.

Verifies the rendered node body (outside ``## Associated Nodes``)
matches what ``build-from-research.py --dry-run`` would regenerate
from the current artifact. Divergence means one of:

  1. Artifact-to-node desync — artifact was edited and re-rendered;
     committer forgot to commit the regenerated node (or the inverse,
     node hand-edit lost on next regen).
  2. Hand-edits to the rendered node body — contributor edited the
     node directly rather than the artifact, breaking the artifact-
     as-source-of-truth invariant.
  3. Renderer changes — build-from-research.py logic changed and the
     committed node bodies haven't been regenerated to match.

Reads ``ctx.regenerated_body`` (lazy ResearchContext property that
spawns the renderer once and caches the output for the lifetime of
the context). Consumes ``ctx.node_path`` for the current rendered
body.

Comparison is byte-equal after the Associated Nodes section is
excised from both sides. Strict byte-equality is load-bearing — the
renderer is deterministic per design.
"""

import re

from checks import Issue


CHECK_NAME = "boundary"


def _excise_associated_nodes(text):
    """Strip the '## Associated Nodes' section (up to the next H2) so
    the boundary diff focuses on the Phase II-rendered body. The
    Associated Nodes section is regenerated by associate.py post-build
    and is not part of build-from-research.py's deterministic output
    (it emits a placeholder).
    """
    pattern = re.compile(
        r"^## Associated Nodes\s*$.*?(?=^## |\Z)",
        re.MULTILINE | re.DOTALL,
    )
    return pattern.sub("", text).rstrip() + "\n"


def check(ctx):
    if ctx.node_path is None:
        return

    regenerated, error = ctx.regenerated_body
    if error is not None:
        yield Issue(
            ctx.rel, "error",
            f"Boundary: {error}",
            check_name=CHECK_NAME,
        )
        return

    current = ctx.node_path.read_text()
    regen_excised = _excise_associated_nodes(regenerated).strip()
    current_excised = _excise_associated_nodes(current).strip()

    if regen_excised != current_excised:
        yield Issue(
            ctx.rel, "error",
            "Boundary: node body diverges from build-from-research.py output. "
            "Either the artifact drifted from the node, or the node was "
            "hand-edited. Re-run build-from-research.py to resync.",
            check_name=CHECK_NAME,
        )
