"""section-rules check — per-node NodeContext check.

Walks ``type_spec.section_rules`` and enforces three sub-rules per
section (per design doc §6 — three sub-checks share H2 extraction and
per-section text retrieval; splitting into three modules would
fragment shared state without buying isolation):

  - ``prose_only``: section must not contain a markdown table
  - ``split: [...]``: section must carry the listed H3 subsections
    (``### Confirmed`` is required when listed; ``### Flagged`` is
    omitted when empty by convention per ``meta/conventions.md``
    "Confirmed vs Flagged", so the walker skips Flagged even when
    listed in the schema's split rule)
  - ``requires_quote_attribution``: any block-quote in the section
    must be paired with an attribution ``| Source | … |`` row

Origin: foundational from the initial commit (``af5f789``). The
``section_rules`` schema mechanism and the check function shipped
together with FOUR rule shapes initially: ``prose_only``, ``split``,
``requires_quote_verification``, and ``auto_generated`` (the latter
applied to ``Associated Nodes``). The check has had two notable
evolutions:

  - ``4dcb1ad`` ("Dead-code removal: 5 verified-unused items"):
    ``auto_generated`` was descriptive-only — never actually
    enforced — and was removed in the dead-code-removal pass. The
    ``Associated Nodes`` section is regenerated by ``associate.py``
    post-build; its skip from this check is via the no-rule path
    (no entry in section_rules) rather than an enforced
    ``auto_generated`` flag.
  - ``31e03fa`` (BACKLOG #19 Phase B / A2 — verbatim-quote-marker
    removal): ``requires_quote_verification`` was renamed to
    ``requires_quote_attribution`` across all 7 section-rule sites.
    Semantic shift, not just rename. The original rule required
    sections to emit per-quote ``Verified:`` rows (output-trust-
    marker shape); after 31e03fa removed the user-facing Verified
    marker per ``meta/conventions.md`` "Confirmation is a
    precondition for inclusion", the rule was reframed to require
    Source attribution rows (input-attribution shape — the
    renderer's ``_render_attribution_block`` helper produces them).
    Same mechanical enforcement (each block-quote needs a paired
    metadata row); different semantics about what that row claims.

Three-sub-rule design preserved at C11: design doc §6 ("Inline
validate_node logic disposition") explicitly chose NOT to split this
module into three (one per sub-rule) — the sub-checks share
``NodeContext.h2_sections`` and ``section_text`` retrieval, and
splitting fragments shared state without buying isolation benefit.
See ``meta/toolkit-notes/c11-validator-decomposition-design.md`` for
the rationale of record.

Migration: ``60bb88d`` (C11 session 3 lift to per-module shape).
Carries three small parsing helpers (``_section_has_table``,
``_count_quote_blocks_and_attributions``,
``_extract_h3_subsections``) inline; only consumer of each was this
walker. C18 confirmed byte-identity through both the
verification→attribution rename and the per-module migration.
"""

import re

from checks import Issue


CHECK_NAME = "section_rules"


def _section_has_table(section_text):
    return bool(
        re.search(r"^\|[^\n]*\|\s*\n\|[\s:|-]+\|", section_text, re.MULTILINE)
    )


def _count_quote_blocks_and_attributions(section_text):
    """Count ``> blockquote`` lines and ``| Source | …`` attribution rows
    in a section. Used to enforce the structural rule that a section
    flagged ``requires_quote_attribution`` either has no quotes (empty
    section is fine) or has a Source row for each quote — the renderer
    always pairs a block-quote with an attribution table whose Source
    row points at the cited archived file.
    """
    quotes = sum(1 for line in section_text.splitlines() if line.strip().startswith(">"))
    attributions = sum(1 for line in section_text.splitlines() if line.strip().startswith("| Source |"))
    return quotes, attributions


def _extract_h3_subsections(section_text):
    return re.findall(r"^### (.+?)\s*$", section_text, re.MULTILINE)


def check(ctx):
    # Direct subscript: every content type declares ``section_rules`` per
    # schema.yaml. Silent fallback to ``{}`` would mask drift if a type
    # loses the block. Loud KeyError per the C21 no-silent-fallbacks
    # principle.
    section_rules = ctx.type_spec["section_rules"]
    h2_sections = ctx.h2_sections
    for section_name, rules in section_rules.items():
        if section_name not in h2_sections:
            continue
        section_text = ctx.section_text(section_name)
        if section_text is None:
            continue

        if rules.get("prose_only") and _section_has_table(section_text):
            yield Issue(
                ctx.rel, "error",
                f"Section '{section_name}' must be prose only (no tables)",
                check_name=CHECK_NAME,
            )

        if "split" in rules:
            h3s = _extract_h3_subsections(section_text)
            for sub in rules["split"]:
                if sub == "Flagged":
                    continue  # omitted when empty by convention
                if sub not in h3s:
                    yield Issue(
                        ctx.rel, "error",
                        f"Section '{section_name}' missing '### {sub}' subsection",
                        check_name=CHECK_NAME,
                    )

        if rules.get("requires_quote_attribution"):
            quotes, attributions = _count_quote_blocks_and_attributions(section_text)
            if quotes > 0 and attributions == 0:
                yield Issue(
                    ctx.rel, "error",
                    f"Section '{section_name}' has quotes but no attribution "
                    f"blocks (each block-quote needs a `| Source | … |` row "
                    f"pointing at the cited archived file)",
                    check_name=CHECK_NAME,
                )
